// Generated by uniffi-bindgen-react-native
#include "signal-native-rn.h"
#include "generated/signal_native.hpp"

namespace signalnativern {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeSignalNative::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}