// Mirrors the Rust types in packages/signal-native/rust/src/lib.rs
// (PreKeyBundleData / EncryptedEnvelope) and their Kotlin/Swift counterparts
// generated by uniffi. Keep in sync by hand for now — see that crate's
// README for the regeneration steps if the Rust API changes.

export type PreKeyBundleData = {
  registrationId: number;
  deviceId: number;
  identityKeyBase64: string;
  oneTimePrekeyId: number;
  oneTimePrekeyPublicBase64: string;
  signedPrekeyId: number;
  signedPrekeyPublicBase64: string;
  signedPrekeySignatureBase64: string;
  kyberPrekeyId: number;
  kyberPrekeyPublicBase64: string;
  kyberPrekeySignatureBase64: string;
};

export type OneTimePrekeyPublic = {
  id: number;
  publicKeyBase64: string;
};

export type EncryptedEnvelope = {
  /** 2 = Whisper (ordinary ratchet message), 3 = PreKey (first message of a new session). */
  messageType: number;
  ciphertextBase64: string;
};
